
version: '3'
services:
  blogging:
    container_name: blogging
    build: 
      context: .
      dockerfile: Dockerfile
    command:
      - "uvicorn"
      - "app:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "9090"
      - "--reload"
    environment:
      PROFILING : true
      LOG_LEVEL: "DEBUG"
      SERVICE_NAME: "blogging"
      POSTGRES_DB: "blogs-db"
      POSTGRES_HOST: "localhost"
      POSTGRES_PORT: "5432"
      POSTGRES_PASSWORD: "Mysql"
      POSTGRES_USER: 'postgres'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 9090:9090
    volumes:
      - ./blogs:/blogs/
